---
- name: Créer les répertoire de Consul Template
  file:
    path: "{{ item }}"
    mode: 0750
    owner: "root"
    group: "consul"
    state: directory
  with_items:
    - "{{ consul_template_config_dir }}"
    - "{{ consul_template_script_dir }}"
    - "{{ consul_template_templates_dir }}"
    - "{{ consul_template_data_dir }}"

- name: Créer le fichier de service systemd pour Consul Template
  template:
    src: consul-template.service.j2
    dest: "{{ consul_template_service_path }}"
    mode: '0644'
