---
- name: Create Syncthing group
  ansible.builtin.group:
    name: syncthing
    state: present

- name: Create Syncthing user
  ansible.builtin.user:
    name: syncthing
    groups: syncthing
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - gnupg
    state: latest

- name: Add the Syncthing APT release key
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.gpg
    keyring: /etc/apt/trusted.gpg.d/syncthing-archive-keyring.gpg

- name: Add the Syncthing repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    filename: syncthing
    state: present

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: syncthing@syncthing.service.d
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: "0744"
  notify:
    - Restart Syncthing

- name: Install syncthing package
  ansible.builtin.apt:
    pkg:
      - syncthing
    state: latest
  notify:
    - Restart Syncthing
