---
- name: Copier les templates de certificat
  copy:
    src: "{{ item }}"
    dest: "{{ consul_template_templates_dir }}/{{ item }}"
  with_items:
    - server-cert.ctmpl
    - server-key.ctmpl
    - server-ca.ctmpl

- name: Copier la configuration de Consul Template
  template:
    src: consul-template.hcl.j2
    dest: "{{ consul_template_config_dir }}/consul-template.hcl"