---
# defaults file for vault_key_value
ansible_python_interpreter: /usr/bin/python3
deploy_vault_secret_dir: "{{ secrets_dir }}/vault"
network_interface: "ens33"
vault_address: "http://{{ hostvars['vault-1']['ansible_'+network_interface]['ipv4']['address'] }}:8200"