---
# defaults file for vault_key_value
ansible_python_interpreter: /usr/bin/python3
deploy_vault_secret_dir: "{{ secrets_dir }}/vault"
network_interface: "ens33"
vault_address: "https://active.vault.service.consul:8200"

vault_tls_directory: '/etc/vault.d/tls'
vault_tls_ca_file: 'vault-agent-ca.pem'