---
# vars/main.yml

consul_ansible_master_group_name: "consul_masters"
vault_ansible_group: "vaults"

consul_ansible_bootstrap_group:
  - "consul-1"
  - "consul-2"
  - "consul-3"

vault_ansible_bootstrap_group:
  - "vault-1"
  - "vault-2"

cert_mode: >-
  {% if inventory_hostname in consul_ansible_bootstrap_group %}
    consul_server
  {% elif inventory_hostname in vault_ansible_bootstrap_group %}
    vault_server
  {% else %}
    client
  {% endif %}
