---
- name: Créer un rôle PKI pour consul-tls
  command: >
    vault write pki/roles/consul-tls
      allowed_domains="{{ pki_allowed_domains }}"
      allow_subdomains=true
      allow_ip_sans=true
      max_ttl="{{ consul_tls_ttl }}"
  environment:
    VAULT_ADDR: "{{ vault_proxy_addr }}"
    VAULT_CACERT: "{{ vault_tls_directory }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  register: pki_consul_tls_role_create
  delegate_to: deploy
  run_once: true
  changed_when: "'role' in pki_consul_tls_role_create.stdout"

- name: Vérifier la création du rôle PKI
  debug:
    msg: "Rôle PKI pour consul-tls créé avec succès."
  when: pki_consul_tls_role_create.changed

- name: Créer un rôle PKI pour vault-tls
  command: >
    vault write pki/roles/vault-tls
      allowed_domains="{{ pki_allowed_domains }}"
      allow_subdomains=true
      allow_ip_sans=true
      max_ttl="{{ vault_tls_ttl }}"
  environment:
    VAULT_ADDR: "{{ vault_proxy_addr }}"
    VAULT_CACERT: "{{ vault_tls_directory }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  register: pki_vault_tls_role_create
  delegate_to: deploy
  run_once: true
  changed_when: "'role' in pki_vault_tls_role_create.stdout"

- name: Vérifier la création du rôle PKI
  debug:
    msg: "Rôle PKI pour vault-tls créé avec succès."
  when: pki_vault_tls_role_create.changed

- name: Créer un rôle PKI pour vault_agent_auth
  command: >
    vault write pki/roles/vault-agent-auth
      allowed_domains="{{ pki_allowed_domains }}"
      allow_subdomains=true
      allow_ip_sans=true
      max_ttl="{{ vault_agent_auth_ttl }}"
  environment:
    VAULT_ADDR: "{{ vault_proxy_addr }}"
    VAULT_CACERT: "{{ vault_tls_directory }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  register: vault_agent_auth_role_create
  delegate_to: deploy
  run_once: true
  changed_when: "'role' in vault_agent_auth_role_create.stdout"

- name: Vérifier la création du rôle PKI
  debug:
    msg: "Rôle PKI pour l'auth des vault-agent créé avec succès."
  when: vault_agent_auth_role_create.changed