---
# vars file for acl-vault-consul
consul_mode: >-
  {% if inventory_hostname in consul_ansible_bootstrap_group %}server{% else %}node{% endif %}
vault_mode: >-
  {% if inventory_hostname in vault_server_group %}server{% else %}client{% endif %}