---
- name: Checking license input variables
  fail:
    msg: You can't use vault_license_file and vault_license_string at the same time
  when: vault_license_file is defined and vault_license_string is defined
