---
- name: Generate vault_local_dir
  file:
    path: "{{ vault_local_dir }}"
    state: directory
    mode: 0750
  delegate_to: localhost
  run_once: true

- name: Vérifier si init.file existe sur un vault
  shell: |
    set -o pipefail
    cat "{{ vault_home_directory }}/init.file" 2>/dev/null | wc -l
  args:
    executable: /bin/bash
  register: init_file_exist
  ignore_errors: true

- name: Unlock secret on vaults
  file:
    path: "{{ vault_home_directory }}"
    owner: root
    recurse: true
    group: "{{ vault_user }}"
    mode: "0700"
  when:
    - init_file_exist.stdout != "0"

- name: Fetch secrets files
  synchronize:
    src: "{{ item }}"
    dest: "{{ vault_local_dir }}"
    mode: pull
  with_items:
    - "{{ vault_home_directory }}/init.file"
    - "{{ vault_home_directory }}/unseal_keys.txt"
    - "{{ vault_home_directory }}/vault_token.txt"
  when: init_file_exist.stdout != "0"

- name: Remove secrets files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ vault_home_directory }}/init.file"
    - "{{ vault_home_directory }}/unseal_keys.txt"
    - "{{ vault_home_directory }}/vault_token.txt"
  when: init_file_exist.stdout != "0"