---
- name: Vérifier et déverrouiller les nœuds Vault
  hosts: vault-1, vault-2
  become: yes
  tasks:

    - name: Vérifier si Vault est initialisé
      shell: |
        export VAULT_ADDR="http://localhost:8200"
        vault status | grep 'Initialized' | awk '{print $2}'
      register: vault_initialized
      changed_when: false
      failed_when: "'Initialized' not in vault_initialized.stdout"

    - name: Copier les clés de déverrouillage depuis deploy
      copy:
        src: "{{ secret_dir }}/vault/unseal_keys.txt"
        dest: "/etc/vault.d/unseal_keys.txt"
      when: vault_initialized is defined and vault_initialized.stdout == "true"
      delegate_to: deploy

    - name: Déverrouiller Vault si initialisé
      shell: |
        export VAULT_ADDR="http://localhost:8200"
        while read -r key; do
          vault operator unseal "$key"
        done < /etc/vault.d/unseal_keys.txt
      args:
        executable: /bin/bash
      when: vault_initialized is defined and vault_initialized.stdout == "true"