---
# vars file for vault_approle_setup
vault_mode: >-
  {% if inventory_hostname in vault_server_group %}server{% else %}client{% endif %}
consul_mode: >-
  {% if inventory_hostname in consul_ansible_bootstrap_group %}server{% else %}client{% endif %}