---
# defaults file for vault-agent-setup
ansible_python_interpreter: /usr/bin/python3
deploy_vault_secret_dir: "{{ secrets_dir }}/vault"
vault_secrets_path: "/etc/vault.d/secrets"
role_id_file_path: "/etc/vault.d/secrets/role_id"
secret_id_file_path: "/etc/vault.d/secrets/secret_id"
sink_path: "/etc/vault.d/secrets/agent-token"

network_interface: "ens33"
vault_api_port: "8200"
vault_agent_dir: "/etc/vault.d/agent/"
vault_agent_templates_dir: "/etc/vault.d/templates"

consul_tls_tmp_directory: '/etc/consul.d/tls/tmp'
consul_tls_directory: '/etc/consul.d/tls'
consul_tls_ca_file: 'consul-agent-ca.pem'
consul_tls_cert_file: 'consul-agent.pem'
consul_tls_key_file: 'consul-agent-key.pem'

vault_principal_addr: "192.168.121.164:8200"
vault_1: "192.168.121.164:8200"
vault_2: "192.168.121.165:8200"
vault_tls_directory: '/etc/vault.d/tls'
vault_tls_ca_file: 'vault-agent-ca.pem'
vault_tls_cert_file: 'vault-agent.pem'
vault_tls_key_file: 'vault-agent-key.pem'

vault_server_group: "{{ groups[vaults_servers_group_name] }}"
consul_ansible_bootstrap_group: "{{ groups[consul_ansible_master_group_name] }}"