---
- name: Install Traefik
  ansible.builtin.unarchive:
    src: https://github.com/traefik/traefik/releases/download/v3.2.0-rc2/traefik_v3.2.0-rc2_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify:
    - Restart Traefik

- name: Create Traefik group
  ansible.builtin.group:
    name: traefik
    state: present

- name: Create Traefik user
  ansible.builtin.user:
    name: traefik
    group: traefik
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Set port binding capability on Traefik
  community.general.capabilities:
    path: /usr/local/bin/traefik
    capability: cap_net_bind_service+ep
    state: present

- name: Copy Traefik config
  ansible.builtin.copy:
    src: traefik
    dest: /etc
    mode: "0755"
  notify:
    - Restart Traefik

- name: Copy Auth Credentials
  ansible.builtin.copy:
    src: basic_auth_credentials
    dest: /etc/traefik/
    mode: "0755"
  notify:
    - Restart Traefik

- name: Copy Acme Token
  ansible.builtin.copy:
    src: acme/acme.json
    dest: /etc/traefik/
    owner: traefik
    group: traefik
    mode: "0600"
  notify:
    - Restart Traefik

- name: Check if consul_http_token is here
  shell: cat /etc/environment | grep "CONSUL_HTTP_TOKEN" | wc -l
  args:
    executable: /bin/bash
  register: consul_http_token_exist
  changed_when: false
  become: no

- debug: msg="consul_http_token exist = {{ consul_http_token_exist.stdout }}"
  when:
      - consul_http_token_exist.stdout == "1"

- name: Create Traefik config file whitout consul
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: "0644"
  when:
    - consul_http_token_exist.stdout == "0"
  notify:
    - Restart Traefik

- name: Get consul_http_token from /etc/environment
  shell: cat /etc/environment | grep "CONSUL_HTTP_TOKEN" | cut -d '=' -f 2
  register: consul_http_token

- name: Create Traefik config file with consul
  ansible.builtin.template:
    src: traefik-consul.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: "0644"
  when:
    - consul_http_token_exist.stdout == "1"
  notify:
    - Restart Traefik

- name: Create Log Folder
  ansible.builtin.file:
    path: /var/log/traefik
    state: directory
    owner: traefik
    group: traefik
    mode: "0744"

- name: Create Plugin-Folder
  ansible.builtin.file:
    path: /etc/traefik/plugins-storage
    state: directory
    owner: traefik
    group: traefik
    mode: "0744"

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: traefik.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: "0644"
  notify:
    - Start Traefik
