---
- name: Download Pi-hole installer
  when: ansible_hostname == "pi-hole-primary"
  ansible.builtin.get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: "0740"

- name: Copy Pi-hole setup config
  when: ansible_hostname == "pi-hole-primary"
  ansible.builtin.copy:
    src: setupVars.conf
    dest: /etc/pihole/
  register: setup_conf_copied

- name: Copy Pi-hole DHCP config
  when: ansible_hostname == "raspberrypi"
  ansible.builtin.copy:
    src: 02-pihole-dhcp.conf
    dest: /etc/dnsmasq.d/
  notify:
    - Restart Pi-hole

- name: Copy Pi-hole DHCP static leases config
  when: ansible_hostname == "raspberrypi"
  ansible.builtin.copy:
    src: 04-pihole-static-dhcp.conf
    dest: /etc/dnsmasq.d/
  notify:
    - Restart Pi-hole

- name: Copy Pi-hole DHCP DNS servers config
  when: ansible_hostname == "raspberrypi"
  ansible.builtin.copy:
    src: 10-pihole-dns-servers.conf
    dest: /etc/dnsmasq.d/
  notify:
    - Restart Pi-hole

- name: Copy Pi-hole Local DNS Records config
  ansible.builtin.copy:
    src: custom.list
    dest: /etc/pihole/
  notify:
    - Restart Pi-hole

- name: Install Pi-hole
  when: setup_conf_copied.changed
  ansible.builtin.command:
    argv:
      - ~/install-pihole.sh
      - --unattended
