---
- name: "Déployer le fichier de configuration de Vault Agent"
  template:
    src: "vault-agent.hcl.j2"
    dest: "{{ vault_agent_config_dir }}/vault-agent.hcl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: '0640'
