---
# tasks file for vault-mtls-consul-certs
- name: Creates tls tmp folder
  ansible.builtin.file:
    path: "{{ consul_tls_directory }}/tmp"
    state: directory
    owner: consul
    group: consul
    mode: 0775

- name: Get /etc/consul.d/tls/tmp/certs.txt
  shell: |
     set -o pipefail
     vault write pki_int/issue/consul-dc1 \
        common_name="{{ inventory_hostname }}.dc1.consul" \
        alt_names="server.dc1.consul" \
        ip_sans="{{ ansible_host }}, 127.0.0.1" \
        format="pem" \
        ttl="24h" > certs.txt
  args:
    executable: /bin/bash
    chdir: "{{ consul_tls_directory }}/tmp"
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_CACERT: "{{ vault_tls_directory }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  changed_when: false

- name: Extract certificate
  shell: |
    grep -Pzo "(?s)(?<=certificate)[^\-]*.*?END CERTIFICATE[^\n]*\n" certs.txt | sed 's/^\s*-/-/g' > consul-agent.pem
  args:
    chdir: "{{ consul_tls_directory }}/tmp"

- name: Extract issuing CA
  shell: |
    # Extraire la chaîne de certificats depuis ca_chain
    grep -Pzo '(?s)ca_chain.*?\]' certs.txt \
      | sed -e 's/ca_chain.*\[//' -e 's/\]//' \
      | sed 's/^\s*-/-/g' > chain_cert.pem

    # Séparer la chaîne en certificats individuels
    awk '/-----BEGIN CERTIFICATE-----/ {n++} {if(n>0) print > "cert_" n ".pem"}' chain_cert.pem

    # Ajouter les deux certificats extraits à consul-agent-ca.pem
    cat cert_1.pem > consul-agent-ca.pem
    cat cert_2.pem >> consul-agent-ca.pem

    # Nettoyage des fichiers temporaires
    rm -f chain_cert.pem cert_1.pem cert_2.pem
  args:
    chdir: "{{ consul_tls_directory }}/tmp"

- name: Format issuing CA
  shell: |
    sed 's/-----END CERTIFICATE----- \+-----BEGIN CERTIFICATE-----/-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----/g' consul-agent-key.pem
  args:
  chdir: "{{ consul_tls_directory }}/tmp"

- name: Extract private key
  shell: |
    grep -Pzo "(?s)(?<=private_key)[^\-]*.*?END RSA PRIVATE KEY[^\n]*\n" certs.txt | sed 's/^\s*-/-/g' > consul-agent-key.pem
  args:
    chdir: "{{ consul_tls_directory }}/tmp"

- name: Set correct permissions for extracted files
  file:
    path: "{{ consul_tls_directory }}/tmp/{{ item.file }}"
    owner: consul
    group: consul
    mode: "{{ item.mode }}"
  loop:
    - { file: 'consul-agent.pem', mode: '0644' }
    - { file: 'consul-agent-ca.pem', mode: '0644' }
    - { file: 'consul-agent-key.pem', mode: '0600' }
