---
- name: Upgrade dependencies
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  tags: always

- name: Install curl
  ansible.builtin.apt:
    pkg:
      - curl
    state: present

- name: Set SSH authorized key
  ansible.posix.authorized_key:
    user: root
    key: ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABgQDk9QtY9gB59lSUcs2Kl0uNX4WW0LWE69fZfRhqYQbtUgdg0CntShrsnFRO0+9DxXX1iL1rvakeQyHBz2I+nG+h5GrdyvphleQuRHO1kZ3KFXYhhZV9gbKMhGkA3vh6BYdVpcLxu/S/FQ8NdfeWpj8BXecRvU/A7/g19nwnOrEctDEFp31+HL7/92lESjqBNMGToXfUpvC8sJw6sBIzzPG2CcjC1fX2+xaGRuumrQieqB5TCd4y8Yu42ymcQVzIW9MLP9523DPQnOuZssT+//LfNLSNQHZ4kJ2E8Qw5MszlQeLXEPns8ui+HsnhlDF+6mW8tB4S3Ow3a1CWTQsNhkqJ0xoY6HsJEaIGVBcs29N1+RM8zsincuGfHOj/Q/RcWm8aSKllUSpkny6CbMyZ58Gqg7nxfSNSZP3SzazZeBz5HbEjKJhJ1KJ4aM6b+UzYA8JsArP/wezvBiolY/ipx8QRithAcdXNu0vZjIaKwT3SxdPkiJJFKBuNM3dWsJWvMnk=
      n43@rog
    state: present
