---
- name: Upgrade dependencies
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  tags: always

- name: Install curl
  ansible.builtin.apt:
    pkg:
      - curl
    state: present

- name: Install gnupg2
  ansible.builtin.apt:
    pkg:
      - gnupg2
    state: present

- name: Install yq
  ansible.builtin.apt:
    pkg:
      - yq
    state: present

- name: Install apt-transport-https
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
    state: present

- name: Install software-properties-common
  ansible.builtin.apt:
    pkg:
      - software-properties-common
    state: present

- name: Install systemd-resolved
  ansible.builtin.apt:
    pkg:
      - systemd-resolved
    state: present
  when: consul_mode == "node"

- name: Install systemd-networkd
  ansible.builtin.apt:
    pkg:
      - systemd-networkd
    state: present

- name: Create /etc/systemd/network directory
  shell: |
    mkdir -p /etc/systemd/network
  args:
    executable: /bin/bash
  become: true

- name: Generate 10-ens33.network configuration
  template:
    src: "10-ens33.network.j2"
    dest: "/etc/systemd/network/10-ens33.network"
    owner: root
    group: root
    mode: 0640

- name: Créer le fichier 60-custom.conf
  copy:
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
      net.ipv6.conf.{{ network_interface }}.disable_ipv6 = 1
    dest: "/etc/sysctl.d/60-custom.conf"
  become: true

- name: Triger sysctl -p
  shell: |
    sysctl -p
  args:
    executable: /bin/bash
  become: true

- name: Triger systemctl restart procps
  shell: |
    systemctl restart procps
  args:
    executable: /bin/bash
  become: true

- name: Remove /etc/resolved.conf
  ansible.builtin.file:
    path: "/etc/resolved.conf"
    state: absent
  when: consul_mode == "node"

- name: Créer le fichier resolved.conf
  copy:
    content: |
      [Resolve]
      DNS=1.1.1.1 1.0.0.1
      FallbackDNS=
    dest: "/etc/systemd/resolved.conf"
  when: consul_mode == "node"

- name: S'assurer que /etc/resolv.conf pointe vers le stub de systemd-resolved
  file:
    src: "/run/systemd/resolve/stub-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link
    force: yes
  when: consul_mode == "node"

- name: Redémarrer systemd-networkd
  service:
    name: systemd-networkd
    state: restarted

- name: Redémarrer systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  when: consul_mode == "node"

- name: Enable ans start systemd-networkd
  ansible.builtin.systemd_service:
    name: systemd-networkd
    state: started
    enabled: true

- name: Enable ans start systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: started
    enabled: true
  when: consul_mode == "node"

- name: Get envoy keering
  shell: |
    set -o pipefail
    wget -q -O - https://apt.envoyproxy.io/signing.key | gpg --dearmor > /etc/apt/keyrings/envoy-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/envoy-keyring.gpg] https://apt.envoyproxy.io bookworm main" > /etc/apt/sources.list.d/envoy.list
  args:
    executable: /bin/bash
  become: true

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install Envoy
  ansible.builtin.apt:
    name: envoy={{ envoy_version }}
    allow_downgrade: yes
    state: present

- name: Set SSH authorized key
  ansible.posix.authorized_key:
    user: root
    key: ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABgQDk9QtY9gB59lSUcs2Kl0uNX4WW0LWE69fZfRhqYQbtUgdg0CntShrsnFRO0+9DxXX1iL1rvakeQyHBz2I+nG+h5GrdyvphleQuRHO1kZ3KFXYhhZV9gbKMhGkA3vh6BYdVpcLxu/S/FQ8NdfeWpj8BXecRvU/A7/g19nwnOrEctDEFp31+HL7/92lESjqBNMGToXfUpvC8sJw6sBIzzPG2CcjC1fX2+xaGRuumrQieqB5TCd4y8Yu42ymcQVzIW9MLP9523DPQnOuZssT+//LfNLSNQHZ4kJ2E8Qw5MszlQeLXEPns8ui+HsnhlDF+6mW8tB4S3Ow3a1CWTQsNhkqJ0xoY6HsJEaIGVBcs29N1+RM8zsincuGfHOj/Q/RcWm8aSKllUSpkny6CbMyZ58Gqg7nxfSNSZP3SzazZeBz5HbEjKJhJ1KJ4aM6b+UzYA8JsArP/wezvBiolY/ipx8QRithAcdXNu0vZjIaKwT3SxdPkiJJFKBuNM3dWsJWvMnk=
      n43@rog
    state: present
