---
- name: Upgrade dependencies
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  tags: always

- name: Install curl
  ansible.builtin.apt:
    pkg:
      - curl
    state: present

- name: Install yq
  ansible.builtin.apt:
    pkg:
      - yq
    state: present

- name: Install systemd-resolved
  ansible.builtin.apt:
    pkg:
      - systemd-resolved
    state: present

- name: Créer le fichier 60-custom.conf
  copy:
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
      net.ipv6.conf.{{ network_interface }}.disable_ipv6 = 1
    dest: "/etc/sysctl.d/60-custom.conf"
  become: true

- name: Triger sysctl -p
  shell: |
    sysctl -p
  args:
    executable: /bin/bash
  become: true

- name: Triger systemctl restart procps
  shell: |
    systemctl restart procps
  args:
    executable: /bin/bash
  become: true

- name: Create resolved.conf.d directory
  file:
    path: "/etc/systemd/resolved.conf.d"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"

- name: Créer le fichier consul.conf
  copy:
    content: |
      [Resolve]
      DNS=127.0.0.1:8600
      Domains='~consul'
    dest: "/etc/systemd/resolved.conf.d/consul.conf"

- name: Remove /etc/systemd/resolved.conf
  ansible.builtin.file:
    path: "/etc/systemd/resolved.conf"
    state: absent

- name: Créer le fichier resolved.conf
  copy:
    content: |
      [Resolve]
      DNS=1.1.1.1 1.0.0.1
      FallbackDNS=8.8.8.8 8.8.4.4
    dest: "/etc/systemd/resolved.conf"

- name: S'assurer que /etc/resolv.conf pointe vers le stub de systemd-resolved
  file:
    src: "/run/systemd/resolve/stub-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link
    force: yes

- name: Redémarrer systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Enable ans start systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: started
    enabled: true

- name: Set SSH authorized key
  ansible.posix.authorized_key:
    user: root
    key: ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABgQDk9QtY9gB59lSUcs2Kl0uNX4WW0LWE69fZfRhqYQbtUgdg0CntShrsnFRO0+9DxXX1iL1rvakeQyHBz2I+nG+h5GrdyvphleQuRHO1kZ3KFXYhhZV9gbKMhGkA3vh6BYdVpcLxu/S/FQ8NdfeWpj8BXecRvU/A7/g19nwnOrEctDEFp31+HL7/92lESjqBNMGToXfUpvC8sJw6sBIzzPG2CcjC1fX2+xaGRuumrQieqB5TCd4y8Yu42ymcQVzIW9MLP9523DPQnOuZssT+//LfNLSNQHZ4kJ2E8Qw5MszlQeLXEPns8ui+HsnhlDF+6mW8tB4S3Ow3a1CWTQsNhkqJ0xoY6HsJEaIGVBcs29N1+RM8zsincuGfHOj/Q/RcWm8aSKllUSpkny6CbMyZ58Gqg7nxfSNSZP3SzazZeBz5HbEjKJhJ1KJ4aM6b+UzYA8JsArP/wezvBiolY/ipx8QRithAcdXNu0vZjIaKwT3SxdPkiJJFKBuNM3dWsJWvMnk=
      n43@rog
    state: present
