---
- name: Get vault_token from deploy secrets
  shell: |
    cat {{ deploy_vault_secret_dir }}/vault_token.txt
  args:
    executable: /bin/bash
  register: vault_parent_token
  delegate_to: deploy
  run_once: true
  become: yes

- name: Vérifier si le moteur K/V est déjà activé
  shell: |
    export VAULT_TOKEN="{{ vault_parent_token.stdout }}"
    export VAULT_ADDR="{{ vault_address }}"
    export VAULT_CACERT="{{ consul_tls_directory }}/{{ consul_tls_ca_file }}"
    vault secrets list -format=json
  args:
    executable: /bin/bash
  register: secrets_list
  delegate_to: deploy
  become: true
  run_once: true
  changed_when: false
  ignore_errors: true

- name: Activer le moteur K/V si non activé
  shell: |
    export VAULT_TOKEN="{{ vault_parent_token.stdout }}"
    export VAULT_ADDR="{{ vault_address }}"
    export VAULT_CACERT="{{ consul_tls_directory }}/{{ consul_tls_ca_file }}"
    vault secrets enable -path=secret kv-v2
  args:
    executable: /bin/bash
  when:
    - secrets_list.stdout is defined
    - "'secret/' not in secrets_list.stdout"
  become: true
  delegate_to: deploy
  run_once: true
