---
- name: Créer des intentions Consul
  command: >
    consul intention create {{ item.key }} {{ item.value }}
  delegate_to: deploy
  run_once: true
  become: yes
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_parent_token.stdout }}"
  loop: "{{ consul_intentions | dict2items }}"
  ignore_errors: true