---
- name: Déployer service-loki.hcl
  copy:
    src: service-loki.hcl
    dest: "{{ consul_dir }}/service-loki.hcl"
    owner: consul
    group: consul
    mode: '0750'
  become: yes
  delegate_to: loki
  run_once: yes

- name: Generate systemd service
  template:
    src: "sidecar-loki.service.j2"
    dest: "/etc/systemd/system/sidecar-loki.service"
    mode: 0640
  become: yes
  delegate_to: loki
  run_once: yes

- name: Make sidecar-loki service available
  service:
    name: "sidecar-loki.service"
    state: started
    enabled: yes
  become: yes
  delegate_to: loki
  run_once: yes

- name: Reload Consul
  systemd:
    name: "consul"
    state: reloaded
    enabled: yes
    daemon_reload: yes
  delegate_to: loki
  run_once: yes
  become: yes

- name: Flush loki configuration
  template:
    src: "loki-config.yml.j2"
    dest: "/etc/loki/config.yml"
    owner: loki
    group: root
    mode: "0755"
  delegate_to: loki
  run_once: yes
  become: yes

- name: Restart Loki service
  ansible.builtin.systemd:
    name: loki
    enabled: yes
    state: restarted
  delegate_to: loki
  run_once: yes
  become: yes