---
- name: Déployer service-promtail.hcl
  template:
    src: service-promtail.hcl.j2
    dest: "{{ consul_dir }}/service-promtail.hcl"
    owner: consul
    group: consul
    mode: '0750'
  become: yes
  when: inventory_hostname != "loki"

- name: Déployer service-promtail.hcl for loki
  copy:
    src: service-promtail-loki.hcl
    dest: "{{ consul_dir }}/service-promtail.hcl"
    owner: consul
    group: consul
    mode: '0750'
  become: yes
  when: inventory_hostname == "loki"

- name: Generate systemd service
  template:
    src: "sidecar-promtail.service.j2"
    dest: "/etc/systemd/system/sidecar-promtail.service"
    mode: 0640
  become: yes
  when: inventory_hostname != "loki"

- name: Make sidecar-promtail service available
  service:
    name: "sidecar-promtail.service"
    state: started
    enabled: yes
  become: yes
  when: inventory_hostname != "loki"

- name: Reload Consul
  systemd:
    name: "consul"
    state: reloaded
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Flush promtail configuration
  template:
    src: "promtail-config.yaml.j2"
    dest: "/opt/promtail/config.yaml"
    owner: promtail
    group: root
    mode: "0755"
  become: yes

- name: Restart promtail service
  ansible.builtin.systemd:
    name: promtail
    enabled: yes
    state: restarted
  become: yes