---
- name: Déployer service-vault.hcl on vaults
  template:
    src: service-vault.hcl.j2
    dest: "{{ consul_dir }}/service-vault.hcl"
    owner: consul
    group: consul
    mode: '0750'
  become: yes
  when: "'vaults' in group_names"

- name: Déployer vault-leader-check.sh on vaults
  template:
    src: vault-leader-check.sh.j2
    dest: "/usr/local/bin/vault-leader-check.sh"
    owner: consul
    group: consul
    mode: '0750'
  become: yes
  when: "'vaults' in group_names"

- name: Generate systemd service on vaults
  template:
    src: "sidecar-vault.service.j2"
    dest: "/etc/systemd/system/sidecar-vault.service"
    mode: 0640
  become: yes
  when: "'vaults' in group_names"

- name: Make sidecar-vault service available on vaults
  service:
    name: "sidecar-vault.service"
    state: started
    enabled: yes
  become: yes
  when: "'vaults' in group_names"

- name: Reload Consul on vaults
  systemd:
    name: "consul"
    state: reloaded
    enabled: yes
    daemon_reload: yes
  when: "'vaults' in group_names"
  become: yes