---
# tasks file for mesh
- name: Call role _get_masters_token
  import_tasks: _get_masters_token.yml

- name: Call role _alertmanager
  import_tasks: _alertmanager.yml

- name: Call role _loki
  import_tasks: _loki.yml

- name: Call role _promtail
  import_tasks: _promtail.yml

- name: Call role _grafana
  import_tasks: _grafana.yml

- name: Call role _intentions.yml
  include_tasks: _intentions.yml