
---
- name: Chown vault
  shell: |
    chown -R {{ vault_user }}:{{ vault_group }} {{ vault_dir }}
  args:
    executable: /bin/bash

- name: Chmod vault
  shell: |
    chmod -R 0750 {{ vault_dir }}
  args:
    executable: /bin/bash

- name: Chown consul
  shell: |
    chown -R {{ consul_user }}:{{ consul_group }} {{ consul_dir }}
  args:
    executable: /bin/bash

- name: Chmod consul
  shell: |
    chmod -R 0750 {{ consul_dir }}
  args:
    executable: /bin/bash

- name: Chown vault secret
  shell: |
    chown -R vault:vault {{ vault_dir }}/secrets
  args:
    executable: /bin/bash

- name: Chmod vault secret
  shell: |
    chmod -R 0700 {{ vault_dir }}/secrets
  args:
    executable: /bin/bash

- name: Chown consul secret
  shell: |
    chown -R consul:consul {{ consul_dir }}/secrets
  args:
    executable: /bin/bash

- name: Chmod consul secret
  shell: |
    chmod -R 0700 {{ consul_dir }}/secrets
  args:
    executable: /bin/bash