---
# defaults file for vault_consul_migration
ansible_python_interpreter: /usr/bin/python3
consul_pki_path: "consul-pki"
connect_pki_path: "connect-pki"
consul_common_name: "consul-ca"
connect_common_name: "connect-ca"
vault_config_dir: "/etc/vault.d"
vault_policies_dir: "{{ vault_config_dir }}/policies"
deploy_vault_secret_dir: "/home/evil/secret/vault"
network_interface: "ens33"

consul_tls_directory: '/etc/consul.d'
consul_tls_ca_file: 'tls/consul-agent-ca.pem'