---
# playbooks/roles/vault_apprle_setup/tasks/_create_policy.yml

- name: Copier la politique consul-template dans le répertoire temporaire
  copy:
    src: consul-template-policy.hcl
    dest: /tmp/consul-template-policy.hcl
  when: active_vault_host is defined

- name: Créer la politique consul-template dans Vault
  shell: |
    export VAULT_TOKEN="{{ vault_parent_token.stdout }}"
    export VAULT_ADDR="{{ vault_addr.stdout }}"
    export VAULT_CACERT="{{ vault_ca_cert.stdout }}"
    vault policy write consul-template-policy /tmp/consul-template-policy.hcl
  args:
    executable: /bin/bash
    removes: /tmp/consul-template-policy.hcl
  when: active_vault_host is defined