---
# playbooks/roles/vault_apprle_setup/tasks/_detect_active_vault.yml
- name: Get vault_token from deploy secrets
  shell: |
    cat {{ deploy_vault_secret_dir }}/vault_token.txt
  args:
    executable: /bin/bash
  register: vault_parent_token
  delegate_to: deploy
  run_once: true
  become: yes

- name: Détecter le nœud Vault actif
  shell: |
    vault status | grep "active" | wc -l
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  args:
    executable: /bin/bash
  register: vault_status
  retries: 10
  delay: 5
  until: vault_status.stdout.strip() == "1"
  ignore_errors: yes

- name: Définir le nœud Vault actif
  set_fact:
    active_vault_host: "{{ inventory_hostname }}"
  when: vault_status.stdout == "1"

- debug: msg="{{ active_vault_host }} is active"
  when:
    - active_vault_host is defined