---
- name: Déployer la configuration de Vault Agent
  template:
    src: "vault-agent.hcl.j2"
    dest: "/etc/vault.d/vault-agent.hcl"
    owner: root
    group: root
    mode: '0644'
  when: alls:!vaults

- name: Créer le répertoire tls de Vault Agent
  file:
    path: "/etc/vault.d/tls"
    state: directory
    owner: vault
    group: vault
    mode: '0755'

- name: Déployer le service systemd pour Vault Agent
  template:
    src: "vault-agent.service.j2"
    dest: "/etc/systemd/system/vault-agent.service"
    owner: root
    group: root
    mode: '0644'
  when: alls:!vaults

- name: Reload le daemon systemd
  systemd:
    daemon_reload: yes
  when: alls:!vaults

- name: Activer et démarrer Vault Agent
  systemd:
    name: vault-agent
    enabled: yes
    state: started
  when: alls:!vaults