---
# playbooks/roles/vault_apprle_setup/tasks/_pki_setup.yml

- name: Vérifier si le moteur PKI est déjà activé
  shell: |
    vault secrets list | grep pki/ | wc -l
  register: pki_status
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  changed_when: false
  when:
    - active_vault_host is defined

- name: Display Pki status
  debug:
    msg: >
      Pki is {{ 'enabled' if pki_status.stdout == "1" else 'not enabled' }} in Vault
  when: active_vault_host is defined

- name: Activer le moteur PKI sur Vault actif si non activé
  command: >
    vault secrets enable -path=pki pki
  when:
    - active_vault_host is defined
    - pki_status.stdout == "0"
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  register: pki_enable_output

- name: Pause de 5s
  command: sleep 5
  run_once: true

- name: Configurer le TTL et le maximum TTL pour le moteur PKI
  command: >
    vault write pki/config/urls
      issuing_certificates="{{ vault_addr }}/v1/pki/ca"
      crl_distribution_points="{{ vault_addr }}/v1/pki/crl"
  when:
    - active_vault_host is defined
    - pki_status.stdout == "0"
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"

- name: Générer le certificat CA racine
  command: >
    vault write -field=certificate pki/root/generate/internal
      common_name="{{ pki_common_name }}"
      ttl="{{ pki_ttl }}"
  register: pki_root_cert
  when:
    - active_vault_host is defined
    - pki_status.stdout == "0"
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"

- name: Configurer le CA racine dans le moteur PKI
  command: >
    vault write pki/config/ca pem_bundle="{{ pki_root_cert.stdout }}"
 when:
    - active_vault_host is defined
    - pki_status.stdout == "0"
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"

- name: Générer le CRL
  command: >
    vault write pki/crl
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
  register: pki_crl
  when:
    - active_vault_host is defined
    - pki_status.stdout == "0"
  environment:
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"

- name: Vérifier la génération du CRL
  debug:
    msg: "CRL généré avec succès."
  when: pki_crl.changed