---
# playbooks/roles/vault_apprle_setup/tasks/_pki_setup.yml

- name: Vérifier si le moteur PKI est déjà activé
  command: vault secrets list -format=json
  register: secrets_list
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
  changed_when: false

- name: Définir si le moteur PKI est activé
  set_fact:
    pki_enabled: "{{ 'pki/' in secrets_list.stdout | from_json }}"

- name: Activer le moteur PKI sur Vault actif si non activé
  command: >
    vault secrets enable -path=pki pki
  when: not pki_enabled
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
  delegate_to: "{{ active_vault_host }}"
  run_once: true
  register: pki_enable_output

- name: Configurer le TTL et le maximum TTL pour le moteur PKI
  command: >
    vault write pki/config/urls
      issuing_certificates="{{ vault_addr }}/v1/pki/ca"
      crl_distribution_points="{{ vault_addr }}/v1/pki/crl"
  when: not pki_enabled
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
  delegate_to: "{{ active_vault_host }}"
  run_once: true