---
# playbooks/roles/vault_apprle_setup/tasks/_renew_secret_id.yml

- name: Générer un nouveau SecretID pour l'AppRole consul-template
  command: vault write -field=secret_id auth/approle/role/consul-template-role/secret-id
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
  register: new_secret_id_output
  tags: renew_secret_id

- name: Mettre à jour le SecretID dans Ansible Vault
  copy:
    dest: "./playbooks/consul_template_approle_credentials.yml"
    content: |
      ---
      consul_template_role_id: "{{ consul_template_role_id }}"
      consul_template_secret_id: "{{ new_secret_id_output.stdout }}"
    mode: '0600'
  when: new_secret_id_output.stdout != consul_template_secret_id
  tags: renew_secret_id

- name: Redémarrer consul-template pour appliquer le nouveau SecretID
  service:
    name: consul-template
    state: restarted
  when: new_secret_id_output.stdout != consul_template_secret_id
  tags: renew_secret_id