---
# tasks file for vault_consul_migration
- name: Activer le moteur PKI pour Consul
  hashivault_secret_engine:
    name: "{{ consul_pki_path }}"
    backend: "pki"
    max_lease_ttl: "87600h"

- name: Générer le certificat CA pour Consul
  hashivault_write:
    path: "{{ consul_pki_path }}/root/generate/internal"
    data:
      common_name: "{{ consul_common_name }}"
      ttl: "87600h"

- name: Créer un rôle pour les serveurs Consul
  hashivault_write:
    path: "{{ consul_pki_path }}/roles/consul-servers"
    data:
      allowed_domains: "consul"
      allow_subdomains: true
      max_ttl: "72h"

- name: Installer Consul Template
  include_role:
    name: consul-template

- name: Copier les templates de certificat
  template:
    src: "{{ item }}"
    dest: "{{ consul_template_templates_dir }}/{{ item }}"
  with_items:
    - server-cert.ctmpl
    - server-key.ctmpl

- name: Copier la configuration de Consul Template
  template:
    src: consul-template.hcl.j2
    dest: "{{ consul_template_config_dir }}/consul-template.hcl"