---
# defaults file for acl-vault-consul
# Utilisateurs et groupes des services
vault_user: vault
vault_group: vault
consul_user: consul
consul_group: consul

# Répertoires à configurer
vault_dirs:
  - /etc/vault.d
consul_dirs:
  - /etc/consul.d