---
- name: Restart Vaults server and unsealed them
  hosts: alls
  become: yes
  vars:
    secrets_dir: "/home/evil/secret"
  tasks:
    - name: Activer et démarrer Consul Template
      systemd:
        name: consul-template
        state: restarted
      become: true

    - name: Redémare Consul
      systemd:
        name: consul
        state: restarted
      become: true