- name: install and configure vault agents on all clients
  hosts: alls
  become: yes
  vars:
    consul_ansible_master_group_name: "consul_masters"
    vaults_servers_group_name: "vaults"
    secrets_dir: "/home/evil/secret"
  roles:
    - vault-agent-setup