---
- name: "Copier le role_id"
  copy:
    content: "{{ approle_role_id.data.role_id }}"
    dest: "{{ vault_agent_role_id_path }}"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: '0400'
  no_log: true

- name: "Copier le secret_id"
  copy:
    content: "{{ approle_secret_id.secret_id }}"
    dest: "{{ vault_agent_secret_id_path }}"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: '0400'
  no_log: true
