---
# vars/main.yml
ansible_python_interpreter: /usr/bin/python3

# Version et URL de téléchargement de Consul Template
consul_template_version: "0.39.1"
consul_template_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
consul_template_download_url: "https://releases.hashicorp.com/consul-template/{{ consul_template_version }}/consul-template_{{ consul_template_version }}_linux_{{ consul_template_architecture }}.zip"
consul_template_sha256_url: "https://releases.hashicorp.com/consul-template/{{ consul_template_version }}/consul-template_{{ consul_template_version }}_SHA256SUMS"

# Chemins d'installation et stockage

vault_token_file: "/etc/vault.d/token"

vault_ca_cert: "/etc/consul.d/tls/consul-agent-ca.pem"
vault_tls_directory: "/etc/consul.d/tls"
vault_tls_ca_cert_file: "consul-agent-ca.pem"

consul_tls_directory: "/etc/consul.d/tls"
consul_tls_ca_cert_file: "consul-agent-ca.pem"
consul_tls_cert_file: "consul-agent.pem"
consul_tls_key_file: "consul-agent-key.pem"

consul_template_install_path: "/usr/local/bin/consul-template"
consul_template_config_dir: "/etc/consul-template.d"
consul_template_data_dir: "/var/lib/consul-template"
consul_template_files_dir: "{{ role_path }}/files"
consul_template_archive_path: "{{ consul_template_files_dir }}/consul-template.zip"
consul_template_sha256_path: "{{ consul_template_files_dir }}/consul-template_SHA256SUMS"
consul_template_extracted_path: "{{ consul_template_files_dir }}/consul-template"
consul_template_service_path: "/etc/systemd/system/consul-template.service"
consul_template_script_dir: "{{ consul_template_config_dir }}/scripts"
consul_template_templates_dir: "{{ consul_template_config_dir }}/templates"
consul_template_start_script_file: "start_consul_template.sh"

deploy_vault_secret_dir: "/home/evil/secret/vault"

vault_address: "{{ lookup('env', 'VAULT_ADDR') | default('', false) }}"
consul_http_addr: "{{ lookup('env', 'CONSUL_HTTP_ADDR') | default('', false) }}"
consul_config_dir: "/etc/consul.d"
consul_user_name: 'consul'