---
http:
  routers:
    to-alertmanager:
      rule: "Host(`alertmanager.korporate.org`)"
      service: alertmanager
      middlewares:
        - "chain-no-auth"

  services:
    alertmanager:
      loadBalancer:
        servers:
          - url: http://10.0.30.23:9093
