---
http:
  routers:
    to-myapp:
      rule: "Host(`myapp.korporate.org`)"
      service: myapp
      middlewares:
        - "chain-no-auth"

  services:
    myapp:
      loadBalancer:
        servers:
          - url: https://10.0.50.21:8443
