---
http:
  routers:
    to-cokpit:
      rule: "Host(`cokpit.korporate.org`)"
      service: cokpit

  services:
    cokpit:
      loadBalancer:
        servers:
          - url: https://10.0.60.250:64294
