---
http:
  routers:
    to-consul:
      rule: "Host(`consul.korporate.org`)"
      service: consul
      middlewares:
        - "chain-no-auth"
    to-consul-secure:
      rule: "Host(`consul.korporate.org`)"
      service: consul
      middlewares:
        - "chain-no-auth"
      tls:
        certResolver: letsencrypt

  services:
    consul:
      loadBalancer:
        servers:
          - url: https://192.168.1.121.161:8443
          - url: https://192.168.1.121.162:8443
          - url: https://192.168.1.121.163:8443
          # - url: http://10.0.20.1:8500
          # - url: http://10.0.20.2:8500
          # - url: http://10.0.20.3:8500