---
http:
  routers:
    to-dev:
      rule: "Host(`dev.korporate.org`)"
      service: dev
      middlewares:
        - "chain-no-auth"

  services:
    dev:
      loadBalancer:
        servers:
          - url: http://10.0.60.250:80
