---
http:
  routers:
    to-grafana:
      rule: "Host(`grafana.korporate.org`)"
      service: grafana
      middlewares:
        - "chain-basic-auth"

  services:
    grafana:
      loadBalancer:
        servers:
          - url: http://10.0.30.20:3000
