---
http:
  routers:
    to-influxdb:
      rule: "Host(`influxdb.korporate.org`)"
      service: influxdb
      middlewares:
        - "chain-basic-auth"

  services:
    influxdb:
      loadBalancer:
        servers:
          - url: 	http://10.0.30.24:8086
