---
http:
  routers:
    to-octant:
      rule: "Host(`octant.korporate.org`)"
      service: octant
      middlewares:
        - "chain-no-auth"

  services:
    octant:
      loadBalancer:
        servers:
          - url: 	http://10.0.50.21:7777
