---
http:
  routers:
    to-prometheus:
      rule: "Host(`prometheus.korporate.org`)"
      service: prometheus
      middlewares:
        - "chain-basic-auth"

  services:
    prometheus:
      loadBalancer:
        servers:
          - url: 	http://10.0.30.21:9090
