---
http:
  routers:
    to-rancher-staging:
      rule: "Host(`rancher-staging.korporate.org`)"
      service: rancher-staging
      middlewares:
        - "chain-no-auth"

  services:
    rancher-staging:
      loadBalancer:
        servers:
          - url: https://10.0.50.21:8443
