---
http:
  routers:
    to-semaphore:
      rule: "Host(`semaphore.korporate.org`)"
      service: semaphore
      middlewares:
        - "chain-no-auth"

  services:
    semaphore:
      loadBalancer:
        servers:
          - url: http://10.0.20.77:3000
