---
http:
  routers:
    to-sonarqube:
      rule: "Host(`sonarqube.korporate.org`)"
      service: sonarqube
      middlewares:
        - "chain-no-auth"

  services:
    sonarqube:
      loadBalancer:
        servers:
          - url: 	http://10.0.20.22:9001
