---
http:
  routers:
    to-teleport:
      rule: "Host(`*.teleport.korporate.org`)"
      service: teleport
      middlewares:
        - "chain-no-auth"

  services:
    teleport:
      loadBalancer:
        servers:
          - url: https://10.0.10.10:3080
