---
http:
  routers:
    to-tpot:
      rule: "Host(`tpot.korporate.org`)"
      service: tpot
      middlewares:
        - "chain-basic-auth"

  services:
    tpot:
      loadBalancer:
        servers:
          - url: 	https://10.0.60.250:64297
