---
http:
  routers:
    to-vault:
      rule: "Host(`vault.korporate.org`)"
      service: vault
      middlewares:
        - "chain-no-auth"
    to-vault-secure:
      rule: "Host(`vault.korporate.org`)"
      service: vault
      middlewares:
        - "chain-no-auth"
      tls:
        certResolver: letsencrypt

  services:
    vault:
      loadBalancer:
        servers:
          - url: http://192.168.1.121.164:8200
          - url: http://192.168.1.121.165:8200
          # - url: http://10.0.20.04:8200
          # - url: http://10.0.20.05:8200