http:
  middlewares:
    chain-basic-auth:
      chain:
        middlewares:
          - middlewares-redirect-errors
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-basic-auth
          - middlewares-compress