---
# defaults file for vault-agent-setup
ansible_python_interpreter: /usr/bin/python3
deploy_vault_secret_dir: "{{ secrets_dir }}/vault"
role_id_file_path: "/etc/vault.d/role_id"
secret_id_file_path: "/etc/vault.d/secret_id"
sink_path: "/etc/vault.d/agent-token"

network_interface: "ens33"
vault_api_port: "8200"
consul_tls_directory: '/etc/consul.d/tls'
consul_tls_ca_file: 'consul-agent-ca.pem'
consul_tls_cert_file: 'consul-agent.pem'
consul_tls_key_file: 'consul-agent-key.pem'
vault_principal_addr: "192.168.121.164:8200"
