---
http:
  routers:
    to-argocd:
      rule: "Host(`argocd.korporate.org`)"
      service: argocd

  services:
    argocd:
      loadBalancer:
        servers:
          - url: https://10.0.50.21:8443
