---
http:
  routers:
    to-minio:
      rule: "Host(`minio.korporate.org`)"
      service: minio
    to-minio-secure:
      rule: "Host(`minio.korporate.org`)"
      service: minio
      tls:
        certResolver: letsencrypt

  services:
    minio:
      loadBalancer:
        servers:
          - url: http://10.0.20.23:9001
          - url: http://10.0.20.24:9001
          - url: http://10.0.20.25:9001