---
http:
  routers:
    to-reverse:
      rule: "Host(`reverse.korporate.org`)"
      service: reverse

  services:
    reverse:
      loadBalancer:
        servers:
          - url: http://10.0.10.11:81
