---
# defaults file for vault_approle_setup
# defaults file for vault_key_value
ansible_python_interpreter: /usr/bin/python3
deploy_vault_secret_dir: "{{ secrets_dir }}/vault"
network_interface: "ens33"
vault_api_port: "8200"

ansible_folder_path: "/home/evil/proxmox-services/ansible"

consul_tls_directory: '/etc/consul.d/tls'
consul_tls_ca_file: 'consul-agent-ca.pem'

vault_addr: "{{ lookup('env', 'VAULT_ADDR') | default('', false) }}"