---
- name: Include my vars
  ansible.builtin.include_vars: /home/brian/dev/my-data/ansible_vars.yml

- name: Install rclone
  ansible.builtin.apt:
    deb: https://downloads.rclone.org/v1.67.0/rclone-v1.67.0-linux-amd64.deb

- name: Copy Rclone config
  ansible.builtin.copy:
    src: /home/brian/dev/my-data/rclone.conf
    dest: /root/.config/rclone/rclone.conf
    mode: "0600"
