---
- name: Créer les répertoire de vault_agent Template
  file:
    path: "{{ item }}"
    mode: 0750
    owner: "root"
    group: "vault"
    state: directory
  with_items:
    - "{{ vault_agent_templates_dir }}"

- name: Déployer le fichier consul-template
  template:
    src: "{{ item }}"
    dest: "{{ vault_agent_templates_dir }}/{{ item | regex_replace('\\.j2$', '') }}"
    owner: "root"
    group: "vault"
    mode: '0750'
  with_items:
    - consul-cert.ctmpl.j2
    - consul-key.ctmpl.j2

- name: Copier les templates de certificat
  copy:
    src: "{{ item }}"
    dest: "{{ vault_agent_templates_dir }}/{{ item }}"
    owner: "root"
    group: "vault"
    mode: '0750'
  with_items:
    - consul-ca.ctmpl