---
- name: Verifie la presence des nvx certificats
  shell: |
    ls {{ consul_tls_tmp_directory }} | wc -l
  args:
    executable: /bin/bash
  register: certs_status

- name: check certs_status
  debug:
    msg: "certs_status= {{ certs_status.stdout }}"

- name: Remplacer les cerificats
  shell: |
    mv {{ consul_tls_tmp_directory }}/* {{ consul_tls_directory }}
    chown -R root:consul {{ consul_tls_directory }}
    chmod -R 750 {{ consul_tls_directory }}
  args:
    executable: /bin/bash
  when: certs_status.stdout == "3"

- name: Reload consul
  systemd:
    name: "consul"
    state: reloaded
    enabled: yes
    daemon_reload: yes

- name: Reload vault serveur
  systemd:
    name: "vault"
    state: reloaded
    enabled: yes
    daemon_reload: yes
  when: vault_mode == "server"

- name: Supprimer le dossier de Certificats temporaire
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
  - "{{ consul_tls_tmp_directory }}"

- name: Déployer la configuration de Vault Agent finale
  template:
    src: "{{ vault_mode }}/vault-agent-approle.hcl.j2"
    dest: "/etc/vault.d/vault-agent.hcl"
    owner: root
    group: root
    mode: '0644'

- name: Restart vault-agent.service
  systemd:
    name: "vault-agent.service"
    state: restarted
    enabled: yes
    daemon_reload: yes