---
- name: Verifie la presence des nvx certificats
  shell: |
    ls {{ consul_tls_tmp_directory }} | wc -l
  args:
    executable: /bin/bash
  register: certs_status

- name: check certs_status
  debug:
    msg: "certs_status= {{ certs_status.stdout }}"

- name: Remplacer les cerificats
  shell: |
    mv {{ consul_tls_tmp_directory }}/* {{ consul_tls_directory }}
    chown -R root:consul {{ consul_tls_directory }}
    chmod -R 750 {{ consul_tls_directory }}
  args:
    executable: /bin/bash
  when: certs_status.stdout == "3"

- name: Reload consul
  systemd:
    name: "consul"
    state: reloaded
    enabled: yes
    daemon_reload: yes

- name: Reload vault serveur
  systemd:
    name: "vault"
    state: reloaded
    enabled: yes
    daemon_reload: yes
  when: vault_mode == "server"

- name: Restart vault-agent.service
  systemd:
    name: "vault-agent.service"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Supprimer le dossier de Certificats temporaire
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
  - "{{ consul_tls_tmp_directory }}"
