---
- name: Supprimer les Certificats et Clés Anciens
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
  - '{{ consul_tls_directory }}/{{ consul_tls_ca_file }}'
  - '{{ consul_tls_directory }}/{{ consul_tls_cert_file }}'
  - '{{ consul_tls_directory }}/{{ consul_tls_key_file }}'

- name: Restart vault-agent.service
  systemd:
    name: "vault-agent.service"
    state: restarted
    enabled: yes
    daemon_reload: yes