---
- name: Déployer la configuration de Vault Agent
  template:
    src: "vault-agent.hcl.j2"
    dest: "/etc/vault.d/vault-agent-client.hcl"
    owner: root
    group: root
    mode: '0644'
  when: "'vaults' not in group_names"

- name: Déployer la configuration de Vault Agent
  template:
    src: "vault-agent.hcl.j2"
    dest: "/etc/vault.d/vault-agent-server.hcl"
    owner: root
    group: root
    mode: '0644'
  when: "'vaults' in group_names"

- name: Déployer le service systemd pour Vault Agent
  template:
    src: "vault-agent.service.j2"
    dest: "/etc/systemd/system/vault-agent.service"
    owner: root
    group: root
    mode: '0644'

- name: Reload le daemon systemd
  systemd:
    daemon_reload: yes

- name: Activer et démarrer Vault Agent
  systemd:
    name: vault-agent
    enabled: yes
    state: restarted