---
- name: Déployer la configuration de Vault Agent temporaire
  template:
    src: "{{ item }}"
    dest: "{{ vault_agent_dir }}/vault-agent.hcl"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "{{ vault_mode }}/vault-agent-approle-tmp.hcl.j2"
    - vault-auth.hcl.j2

- name: Déployer le service systemd pour Vault Agent
  template:
    src: "vault-agent.service.j2"
    dest: "/etc/systemd/system/vault-agent.service"
    owner: root
    group: root
    mode: '0644'

- name: Reload le daemon systemd
  systemd:
    daemon_reload: yes

- name: Activer et démarrer Vault Agent
  systemd:
    name: vault-agent
    enabled: yes
    state: restarted