---
# playbooks/roles/vault_apprle_setup/tasks/_create_approle.yml

- name: Get list of enabled auth methods from Vault
  shell: |
    vault auth list | grep 'approle/' | wc -l
  register: approle_enabled
  environment:
    VAULT_ADDR: "https://{{ hostvars[inventory_hostname]['ansible_'+network_interface]['ipv4']['address'] }}:{{ vault_api_port }}"
    VAULT_CACERT: "{{ consul_tls_directory }}/{{ consul_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  failed_when: approle_enabled.rc != 0
  when: active_vault_host is defined
  changed_when: false

- name: Display AppRole status
  debug:
    msg: >
      AppRole is {{ 'enabled' if approle_enabled.stdout == "1" else 'not enabled' }} in Vault
  when: active_vault_host is defined

- name: Activation de Approle dans le vault actif
  shell: |
    vault auth enable approle
  args:
    executable: /bin/bash
  environment:
    VAULT_ADDR: "https://{{ hostvars[inventory_hostname]['ansible_'+network_interface]['ipv4']['address'] }}:{{ vault_api_port }}"
    VAULT_CACERT: "{{ consul_tls_directory }}/{{ consul_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  when:
    - active_vault_host is defined
    - approle_enabled.stdout == "0"

- name: check if approle vault-agent is already writed
  shell: |
    vault read auth/approle/role/vault-agent-role | grep vault-agent-policy | wc -l
  register: approle_already_writed
  environment:
    VAULT_ADDR: "https://{{ hostvars[inventory_hostname]['ansible_'+network_interface]['ipv4']['address'] }}:{{ vault_api_port }}"
    VAULT_CACERT: "{{ consul_tls_directory }}/{{ consul_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  failed_when: approle_already_writed.rc != 0
  when: active_vault_host is defined
  changed_when: false

- name: Display AppRole vault_agent status
  debug:
    msg: >
      AppRole vault_agent is {{ 'already' if approle_already_writed.stdout == "1" else 'not' }} in Vault
  when: active_vault_host is defined

- name: Créer l'AppRole vault-agent dans Vault
  shell: |
    vault write auth/approle/role/vault-agent-role \
    token_policies="vault-agent-policy" \
    token_ttl=24h \
    token_max_ttl=72h \
    secret_id_ttl=0
  environment:
    VAULT_ADDR: "https://{{ hostvars[inventory_hostname]['ansible_'+network_interface]['ipv4']['address'] }}:{{ vault_api_port }}"
    VAULT_CACERT: "{{ consul_tls_directory }}/{{ consul_tls_ca_file }}"
    VAULT_TOKEN: "{{ vault_parent_token.stdout }}"
  args:
    executable: /bin/bash
  register: approle_creation
  when:
    - active_vault_host is defined
    - approle_already_writed.stdout == "0"
  changed_when: "'key' in approle_creation.stdout"
