---
- name: Create qBittorrent group
  ansible.builtin.group:
    name: qbittorrent
    state: present

- name: Create qBittorrent user
  ansible.builtin.user:
    name: qbittorrent
    groups: qbittorrent
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - gnupg
    state: latest

- name: Add qBittorrent stable repository from PPA and install its signing key
  ansible.builtin.apt_repository:
    repo: ppa:qbittorrent-team/qbittorrent-stable

- name: Install qBittorrent
  ansible.builtin.apt:
    pkg:
      - qbittorrent-nox
    state: latest
    update_cache: true

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: qbittorrent.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start qBittorrent
